SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, B.MAX_COL - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A, (
        SELECT MAX(SIZE_OF_COLONY) AS MAX_COL, YEAR(DIFFERENTIATION_DATE) AS YYEAR
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)
    ) AS B
WHERE YEAR(A.DIFFERENTIATION_DATE) = B.YYEAR
ORDER BY YEAR, YEAR_DEV